// src/pages/TableView.js
import React, { useState } from "react";
import SearchFilters from "../components/SearchFilters";
import RecordsTable from "../components/RecordsTable";

// COMPLETE MOCK DATA: 10 example records
const exampleRecords = [
  {
    feedback_received_date: "2025-11-27",
    record_id: "INC0001",
    patient_full_name: "Patient 1",
    issuing_department: "ER",
    target_department: "Ward 1",
    source_1: "Phone",
    feedback_type: "Complaint",
    domain: "Clinical",
    category: "Safety",
    sub_category: "Neglect -General",
    classification_ar: "تصنيف 1",
    complaint_text: "This is a sample complaint text for record 1.",
    immediate_action: "Action 1",
    taken_action: "Taken Action 1",
    severity_level: "High",
    stage: "Admission",
    harm_level: "Low",
    status: "In Progress",
    improvement_opportunity_type: "Yes"
  },
  {
    feedback_received_date: "2025-11-26",
    record_id: "INC0002",
    patient_full_name: "Patient 2",
    issuing_department: "ICU",
    target_department: "Ward 2",
    source_1: "Walk-in",
    feedback_type: "Suggestion",
    domain: "Management",
    category: "Quality",
    sub_category: "Absent Communication",
    classification_ar: "تصنيف 2",
    complaint_text: "This is a sample complaint text for record 2.",
    immediate_action: "Action 2",
    taken_action: "Taken Action 2",
    severity_level: "Medium",
    stage: "Care",
    harm_level: "Medium",
    status: "Closed",
    improvement_opportunity_type: "No"
  },
  {
    feedback_received_date: "2025-11-25",
    record_id: "INC0003",
    patient_full_name: "Patient 3",
    issuing_department: "Ward 1",
    target_department: "ER",
    source_1: "Email",
    feedback_type: "Complaint",
    domain: "Relational",
    category: "Environment",
    sub_category: "Accomodation",
    classification_ar: "تصنيف 3",
    complaint_text: "This is a sample complaint text for record 3.",
    immediate_action: "Action 3",
    taken_action: "Taken Action 3",
    severity_level: "Low",
    stage: "Discharge",
    harm_level: "High",
    status: "In Progress",
    improvement_opportunity_type: "Yes"
  },
  {
    feedback_received_date: "2025-11-24",
    record_id: "INC0004",
    patient_full_name: "Patient 4",
    issuing_department: "Radiology",
    target_department: "Ward 1",
    source_1: "Phone",
    feedback_type: "Suggestion",
    domain: "Clinical",
    category: "Safety",
    sub_category: "Bureaucracy",
    classification_ar: "تصنيف 4",
    complaint_text: "This is a sample complaint text for record 4.",
    immediate_action: "Action 4",
    taken_action: "Taken Action 4",
    severity_level: "High",
    stage: "Care",
    harm_level: "Medium",
    status: "Closed",
    improvement_opportunity_type: "No"
  },
  {
    feedback_received_date: "2025-11-23",
    record_id: "INC0005",
    patient_full_name: "Patient 5",
    issuing_department: "Cardiology",
    target_department: "ER",
    source_1: "Walk-in",
    feedback_type: "Complaint",
    domain: "Management",
    category: "Quality",
    sub_category: "Clinician -Errors",
    classification_ar: "تصنيف 5",
    complaint_text: "This is a sample complaint text for record 5.",
    immediate_action: "Action 5",
    taken_action: "Taken Action 5",
    severity_level: "Medium",
    stage: "Admission",
    harm_level: "Low",
    status: "In Progress",
    improvement_opportunity_type: "Yes"
  },
  {
    feedback_received_date: "2025-11-22",
    record_id: "INC0006",
    patient_full_name: "Patient 6",
    issuing_department: "Admin",
    target_department: "ICU",
    source_1: "Email",
    feedback_type: "Suggestion",
    domain: "Relational",
    category: "Environment",
    sub_category: "Delay -Access",
    classification_ar: "تصنيف 6",
    complaint_text: "This is a sample complaint text for record 6.",
    immediate_action: "Action 6",
    taken_action: "Taken Action 6",
    severity_level: "Low",
    stage: "Discharge",
    harm_level: "High",
    status: "Closed",
    improvement_opportunity_type: "No"
  },
  {
    feedback_received_date: "2025-11-21",
    record_id: "INC0007",
    patient_full_name: "Patient 7",
    issuing_department: "ER",
    target_department: "Cardiology",
    source_1: "Phone",
    feedback_type: "Complaint",
    domain: "Clinical",
    category: "Safety",
    sub_category: "Delay -General",
    classification_ar: "تصنيف 7",
    complaint_text: "This is a sample complaint text for record 7.",
    immediate_action: "Action 7",
    taken_action: "Taken Action 7",
    severity_level: "High",
    stage: "Care",
    harm_level: "Medium",
    status: "In Progress",
    improvement_opportunity_type: "Yes"
  },
  {
    feedback_received_date: "2025-11-20",
    record_id: "INC0008",
    patient_full_name: "Patient 8",
    issuing_department: "Ward 2",
    target_department: "Radiology",
    source_1: "Walk-in",
    feedback_type: "Suggestion",
    domain: "Management",
    category: "Quality",
    sub_category: "Delayed Communication",
    classification_ar: "تصنيف 8",
    complaint_text: "This is a sample complaint text for record 8.",
    immediate_action: "Action 8",
    taken_action: "Taken Action 8",
    severity_level: "Medium",
    stage: "Admission",
    harm_level: "Low",
    status: "Closed",
    improvement_opportunity_type: "No"
  },
  {
    feedback_received_date: "2025-11-19",
    record_id: "INC0009",
    patient_full_name: "Patient 9",
    issuing_department: "ICU",
    target_department: "Admin",
    source_1: "Email",
    feedback_type: "Complaint",
    domain: "Relational",
    category: "Environment",
    sub_category: "Dimissing Patients",
    classification_ar: "تصنيف 9",
    complaint_text: "This is a sample complaint text for record 9.",
    immediate_action: "Action 9",
    taken_action: "Taken Action 9",
    severity_level: "Low",
    stage: "Discharge",
    harm_level: "High",
    status: "In Progress",
    improvement_opportunity_type: "Yes"
  },
  {
    feedback_received_date: "2025-11-18",
    record_id: "INC0010",
    patient_full_name: "Patient 10",
    issuing_department: "Radiology",
    target_department: "Ward 2",
    source_1: "Phone",
    feedback_type: "Suggestion",
    domain: "Clinical",
    category: "Safety",
    sub_category: "Disrespect",
    classification_ar: "تصنيف 10",
    complaint_text: "This is a sample complaint text for record 10.",
    immediate_action: "Action 10",
    taken_action: "Taken Action 10",
    severity_level: "High",
    stage: "Care",
    harm_level: "Medium",
    status: "Closed",
    improvement_opportunity_type: "No"
  }
];

const TableView = () => {
  const [filters, setFilters] = useState({
    searchText: "",
    issuingDept: "All",
    targetDept: "All",
    source: "All"
  });

  return (
    <div style={{ padding: "20px" }}>
      <h1>Table View</h1>
      <SearchFilters filters={filters} setFilters={setFilters} />
      <RecordsTable records={exampleRecords} filters={filters} />
    </div>
  );
};

export default TableView;
